### ISSUE TITLE
Learn git 

### ISSUE THREAD

**Issue by andrewdacenko** [denmig/1st-project#1]
Learn command line interface.

Create 4 branches. 
- master
- develop
- feature/learn-git
- feature/some-conflict

Protect develop branch and master from removal and direct commits. Allow only rebasing.

Make multiple dummy commits to feature branch.

Push them and create merge request to develop.

At the same time make multiple commits to second feature branch. 

Do same stuff for it.

Accept first feature to develop.

Try to resolve conflicts on second one.

Remove branches after merging.

Keep develop and master only.

**Comment by denmig** [comment]
done

**Comment by denmig** [comment]
close #1
